### ISSUE TITLE
Running `powermon -h` causes No translation file found for domain: 'powermon'

### ISSUE THREAD

**Issue by diminDDL** [jblance/powermon#17]
After installing powermon on a fresh raspberry pi os install with `pip install powermon[api]` and trying to run `powermon -h`, the following is returned:
```
Traceback (most recent call last):
  File "/home/pi/.local/bin/powermon", line 5, in <module>
    from powermon.runner import main
  File "/home/pi/.local/lib/python3.11/site-packages/powermon/runner.py", line 17, in <module>
    from powermon.device import Device
  File "/home/pi/.local/lib/python3.11/site-packages/powermon/device.py", line 19, in <module>
    lang = gettext.translation('powermon', localedir='locales', languages=['en'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/gettext.py", line 531, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'powermon'
```

Manually copying the `locales` directory into my home folder and running the command from there seems to have fixed the issue. I also tried placing the `locales` folder into `~/.local/lib/python3.11/site-packages/powermon` but that didn't do anything.

**Comment by jblance** [comment]
hopefully version 1.0.17 fixes this bug
